Ekartproject/Ekartapp/urls.py
from django.urls import path
from . import views

app_name = 'Ekartapp'
urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='Products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='proCatdetail'),
]

Ekartproject/Ekartproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Ekartapp/', include('Ekartapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ekartproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

Ekartproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.SearchResult, name='SearchResult'),
]

Ekartproject/Ekartapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return  reverse('Ekartapp:Products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return  reverse('Ekartapp:proCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

Ekartproject/cart/models.py
from django.db import models
from Ekartapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

Ekartproject/search_app/models.py
from django.db import models

# Create your models here.

Ekartproject/Ekartapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

Ekartproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Ekartapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

Ekartproject/search_app/views.py
from django.shortcuts import render
from Ekartapp.models import Product
from django.db.models import Q


# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

Ekartproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
  </div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap@4.0.0/dist/js/bootstrap.min.js' %}"></script>
</body>
</html>

Ekartproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page. Proceed to review your items and place the order
{% endblock %}
{% block title %}
    Cart -connect
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please click<a href="{% url 'Ekartapp:allProdCat' %}">Here</a>to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart
        </h1>
        <br>
    </div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"> </a>

                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: $  {{cart_item.product.price}}
                    <br>
                    Qty :  {{cart_item.quantity}} x $  {{cart_item}}
                </td>
                <td>
                    $  {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < car_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %} " class="custom_a"><i class="uil uil-plus-circle"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="uil uil-minus-circle"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="uil uil-trash-alt"></i></a>
                </td>
                {% else %}
                <td>
                     <a href="{% url 'cart:add_cart' cart_item.product.id %} " class="custom_a"><i class="uil uil-plus-circle"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="uil uil-minus-circle"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="uil uil-trash-alt"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                please review your cart items before proceeding with order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your total is: <strong>{{total}}</strong>
            </td>
        </tr>
        </tbody>
    </table>
<div class="mx-auto">
    <a href="{% url 'Ekartapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button" style="width:100px; height:40px">Continue</a>
    <a href="{% url 'Ekartapp:allProdCat' %}" class="btn btn-warning btn-block my_custom_button" style="width:100px; height:40px margin-top:10px">Payment</a>
    </div>

    {% endif %}
</div>
</div>
</div>

{% endblock %}

Ekartproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{category.description|truncatewords:200 }}
   {% else %}
       Welcome To KRISHNA BAKERY where you can buys different items.....
   {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
      {{category.name}} - KRISHNA BAKERY
   {% else %}
      TASTE OUR NEW ITEMS - KRISHNA BAKERY
   {% endif %}
{% endblock %}


{% block content %}
    {% if category %}

           <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a href="{% url 'Ekartapp:allProdCat' %}">Taste Of Loves</a></p>
            </div>
                </div>
        </div>
    {% endif %}
       <div class="ma_auto">
    {% if category %}
            <img class="my_image" style="width:100%; height:600px;" src="{{category.image.url}}" alt="{{category.name}}">
       </div>
       <br>
         <div>
             <h1 class="cat" style="font-size:30px; text-transform: uppercase; font-family:Times New Roman, Times, serif; text-align:center;">{{category.name}}</h1>
             <p class="text-justify" style="font-family:Lucida Sans; font-size:15px">{{category.description}}</p>

</div>
    {% else %}
<div>
<img class="my_image my_image_padding" src="{%  static 'img/card.png' %}" alt="Our Products" width="100%" height="600px">
</div>
<br>
<div>
    <h1 class="text-center my_title" style="font-size:30px; text-transform: uppercase; font-family:Times New Roman, Times, serif;">Taste Of Loves</h1>
    <p class="text-justify" style="font-family:Lucida Sans; font-size:20px">Restaurant menu descriptions play an essential role in the restaurant menu design. In most restaurants, descriptions are a list of all the ingredients that are used to prepare the dish. A stellar restaurant menu descriptions can be so much more than that!!!! </p>
</div>
  {% endif %}

<div class="container margin-bottom:10px">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-6 col-lg-6" style="margin-bottom:25px;">
            <div class="card text-center" style="min-width:18rem,">
                <a href="{{product.get_url}}"><img class="my_image" style="width:50%; height:300px;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body" style="padding-top:10px">
                    <h4 class="head" style="font-size:20px; text-transform: uppercase; letter-spacing:.2em; font-family:Times New Roman, Times, serif;">{{product.name}}</h4>
                    <p class="price" style="font-size:18px; font-weight:bold">${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
         {% csrf_token %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
                   {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

Ekartproject/templates/footer.html
<div class="footer navbar-bottom my_footer" style=" background-color: LightGoldenrodYellow; height:20px; margin-top:15px">
    <p class="text-center" style="font-size:10px"><i>&Copy; ANCHOVE RESTAURANT pvt ltd. All Right Reserved</i></p>
</div>

Ekartproject/templates/header.html
{% load static %}
<header>
     <center>
         <a href="{% url 'Ekartapp:allProdCat' %}"></a> <img src="{% static 'img/logo.jpg' %}" alt="log img" width="300px";>
       </center>
</header>

Ekartproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#"><i class="uil uil-home"></i>HOME</a>
        </li>
        <li class="nav-item dropdown {% if 'Ekartapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="uil uil-shopping-bag"></i>SHOP
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Ekartapp:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}" ><i class="uil uil-shopping-cart-alt"></i>({{item_count}}) </a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="uil uil-search"></i></button>
      </form>
    </div>
  </div>
</nav>

Ekartproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      {{product.description|truncatewords:200 }}


{% endblock %}
{% block title %}
   {% if category %}
      {{product.name}} - Taste Product
   {
   {% endif %}
{% endblock %}
{% block content %}

<div>
    <div>
        <p><a href="{% url 'Ekartapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<br>
<div>
    <div class="container">
        <div class="text-center">
            <img class="my_image" style="width:30%; height:300px;" src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
     <div>
        <div>
            <h1 class="prod " style="font-size:30px; text-transform : uppercase; font-family:Times New Roman, Times, serif;">{{product.name}}</h1>
            <p class="price" style="font-size:18px; font-weight:bold">${{product.price}}</p>
            <p class="title" style="font-size:20px; text-transform : uppercase; font-family:Times New Roman, Times, serif;">Product Description</p>
            <p class="para" style="font-family:italic small-caps bold 12px/30px Georgia, serif; font-size:15px">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p><b><i>OUT OF STOCK</i></b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">ADD CART</a>
            <a class="btn btn-warning" href="{% url 'cart:add_cart' product.id %}">BUY NOW</a>
            {% endif %}
            {% endblock %}

        </div>
    </div>
</div>

Ekartproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    We have variety of food item.
{% endblock %}
{% block title %}
    search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> you have searched for:<b>"{{query}}"</b> </p>
</div>
<div class="container margin-bottom:10px">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-6 col-lg-6">
            <div class="card text-center" style="min-width:18rem,">
                <a href="{{product.get_url}}"><img class="my_image" style="width:70%; height:300px;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body" style="padding-top:10px">
                    <h4 class="head" style="font-size:20px; text-transform: uppercase; letter-spacing:.2em; font-family:Times New Roman, Times, serif;">{{product.name}}</h4>
                    <p class="price" style="font-size:18px; font-weight:bold">${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text"> result not found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}